critical:
  - '/(\s|^)(critical|urgent)(:|\s|$)/i'

enhancement:
  - '/(\s|^)(feat|features|request|new|improve|create|build|enhancement|rework|effects?)(:|\s|$)/i'

bug:
  - '/(\s|^)(bug|fix|issue|solve|correct|defect)(:|\s|$)/i'

documentation:
  - '/(\s|^)(docs|document|documentation|readme)(:|\s|$)/i'

invalid:
  - '/(\s|^)(invalid)(:|\s|$)/i'

help wanted:
  - '/(\s|^)(help|need|info)(:|\s|$)/i'

effect:
  - '/(\s|^)(effects?)(:|\s|$)/i'
