critical:
  - '/(critical|urgent)/i'

enhancement:
  - '/(feat|features|request|new|improve|create|build|enhancement|rework|effects?)/i'

bug:
  - '/(bug|fix|issue|solve|correct|defect)/i'

documentation:
  - '/(docs|document|documentation|readme)/i'

invalid:
  - '/(invalid)/i'

help wanted:
  - '/(help|need|info)/i'

effect:
  - '/(effects?)/i'
