target-version = "py312"

# Allow lines to be as long as 120.
line-length = 100

[lint]
select = [
    "ALL",
]

ignore = [
    "ANN401", # Dynamically typed expressions (typing.Any) are disallowed
    "D203", # no-blank-line-before-class (incompatible with formatter)
    "D212", # multi-line-summary-first-line (incompatible with formatter)
    "FIX002", # Line contains TODO, consider resolving an issue
    "TD003", # Missing issue link on the line following this TODO
    "ASYNC230", # Async functions should not open files with blocking methods
    "ASYNC210", # Async functions should not call blocking HTTP methods
    "LOG015" # info() call on root logger
]
