substitutions:
  device: esp-matrix-lamp
  name: ESPHome Matrix Lamp

esp32:
  board: esp32-c3-devkitm-1

dashboard_import:
  package_import_url: github://andrewjswan/matrix-lamp/matrix_lamp_esp32c3.yaml@main

packages:
  common: !include packages/common.yaml
  base: !include packages/matrix_lamp_base.yaml
  light: !include packages/matrix_lamp_light.yaml
  button: !include packages/matrix_lamp_button.yaml
