substitutions:
  device: esp-matrix-lamp
  name: ESPHome Matrix Lamp

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino
    version: latest

dashboard_import:
  package_import_url: github://andrewjswan/matrix-lamp/matrix_lamp_esp32s3.yaml@main

packages:
  common: !include packages/common.yaml
  base: !include packages/matrix_lamp_base.yaml
  light: !include packages/matrix_lamp_light.yaml
  sunrise: !include packages/matrix_lamp_sunrise.yaml
  ddp: !include packages/matrix_lamp_ddp.yaml
  button: !include packages/matrix_lamp_button.yaml
