substitutions:
  device: "esp_matrix_lamp"
  name: "matrix-lamp"
  friendly_name: "ESPHome Matrix Lamp"
  pin_button: "GPIO10"

esp32:
  board: esp32-c3-devkitm-1

dashboard_import:
  package_import_url: github://andrewjswan/matrix-lamp/matrix_lamp_esp32c3.yaml@main

packages:
  common: !include packages/common.yaml
  base: !include packages/matrix_lamp_base.yaml
  control: !include packages/matrix_lamp_control.yaml
  light: !include packages/matrix_lamp_light.yaml
  sunrise: !include packages/matrix_lamp_sunrise.yaml
  ddp: !include packages/matrix_lamp_ddp.yaml
  button: !include packages/matrix_lamp_button.yaml
  power: !include packages/matrix_lamp_power.yaml
  random: !include packages/matrix_lamp_random.yaml
