substitutions:
  device: "esp_matrix_lamp"
  name: "matrix-lamp"
  friendly_name: "ESPHome Matrix Lamp"
  pin_pullup: "false"

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

dashboard_import:
  package_import_url: github://andrewjswan/matrix-lamp/matrix_lamp_esp32.yaml@main

packages:
  common: !include packages/common.yaml
  base: !include packages/matrix_lamp_base.yaml
  control: !include packages/matrix_lamp_control.yaml
  light: !include packages/matrix_lamp_light.yaml
  sunrise: !include packages/matrix_lamp_sunrise.yaml
  ddp: !include packages/matrix_lamp_ddp.yaml
  button: !include packages/matrix_lamp_button.yaml
  power: !include packages/matrix_lamp_power.yaml
  random: !include packages/matrix_lamp_random.yaml
  # music: !include packages/matrix_lamp_music.yaml
  # espnow: !include packages/matrix_lamp_espnow_music_leds_slave.yaml
