substitutions:
  max_threshold: "5000"

sensor:
  # Grid Power Sensor
  - platform: homeassistant
    id: grid_power
    entity_id: sensor.grid_power

light:
  # Power Effects
  - id: !extend neopixel_led
    effects:
      - addressable_lambda:
          name: Power Bubbles
          update_interval: 16ms  # ~60 FPS
          lambda: |-
            if (initial_run) {
              ESP_LOGD("effect", "Power Bubbles");

              it.all() = Color::BLACK;
              fastled_helper::InitLeds(it.size());
            }

            // Smooth out grid power readings using a low-pass filter
            static float filtered_power = 0;
            float grid_power_value = 0;

            if (id(grid_power).has_state()) {
              grid_power_value = id(grid_power).state;
            }
            filtered_power = 0.9f * filtered_power + 0.1f * grid_power_value;

            // Calculate effect density based on the maximum threshold
            float density = filtered_power / ${max_threshold}.0f;
            if (density > 1.0f) density = 1.0f;
            if (density < 0.0f) density = 0.0f;

            int new_bubbles = int(density * WIDTH);

            for (int r = 0; r < MAX_Y; r++) {
              for (int c = 0; c < WIDTH; c++) {
                uint32_t raw_color = getPixColorXY(c, r + 1);
                drawPixelXY(c, r, CRGB(raw_color));
              }
            }
            for (int c = 0; c < WIDTH; c++) {
              drawPixelXY(c, MAX_Y, CRGB::Black);
            }

            // Generate brand new bubbles straight
            for (int i = 0; i < new_bubbles; i++) {
              int col = rand() % WIDTH;

              int r_val = int(255 * density);
              int g_val = int(255 * (1.0f - density));

              CRGB bubble_color;
              bubble_color = CRGB(r_val, g_val, 0);

              drawPixelXY(col, MAX_Y, bubble_color);
            }

            for (unsigned i = 0; i < it.size(); i++) {
              it[i] = Color(fastled_helper::leds[i].r, fastled_helper::leds[i].g, fastled_helper::leds[i].b);
            }
