substitutions:
  num_leds: "256"
  type_leds: "GRB"
  pin_leds: "GPIO3"
  color_correct_bright: "100%"

light:
  # Neopixel with Matrix Lamp
  - platform: esp32_rmt_led_strip
    id: neopixel_led
    icon: mdi:lava-lamp
    rgb_order: ${type_leds}
    pin: ${pin_leds}
    num_leds: ${num_leds}
    name: RMT Light
    color_correct: [$color_correct_bright, $color_correct_bright, $color_correct_bright]
    chipset: WS2812
