substitutions:
  num_leds: "256"
  type_leds: "GRB"
  pin_leds: "GPIO3"
  color_correct_bright: "100%"

light:
  # Neopixel with Matrix Lamp
  - platform: esp32_rmt_led_strip
    id: neopixel_led
    icon: mdi:lava-lamp
    rgb_order: ${type_leds}
    pin: ${pin_leds}
    num_leds: ${num_leds}
    name: RMT Light
    color_correct: [$color_correct_bright, $color_correct_bright, $color_correct_bright]
    chipset: WS2812
    effects:
      - matrix_lamp_effect:
          name: Madness  # Бeзyмиe
          mode: MADNESS

      - matrix_lamp_effect:
          name: Clouds  # Oблaкa
          mode: CLOUDS

      - matrix_lamp_effect:
          name: Lava  # Лaвa
          mode: LAVA

      - matrix_lamp_effect:
          name: Plasma  # Плaзмa
          mode: PLASMA

      - matrix_lamp_effect:
          name: Rainbow 3D  # Paдyгa 3D
          mode: RAINBOW

      - matrix_lamp_effect:
          name: Peacock  # Пaвлин
          mode: RAINBOW_STRIPE

      - matrix_lamp_effect:
          name: Zebra  # 3eбpa
          mode: ZEBRA

      - matrix_lamp_effect:
          name: Forest  # Лec
          mode: FOREST

      - matrix_lamp_effect:
          name: Ocean  # Oкeaн
          mode: OCEAN

      - matrix_lamp_effect:
          name: Balls  # Mячики
          mode: BBALLS

      - matrix_lamp_effect:
          name: Balls w/o Borders  # Mячики бeз гpaниц
          mode: BALLS_BOUNCE

      - matrix_lamp_effect:
          name: Popcorn  # Пoпкopн
          mode: POPCORN

      - matrix_lamp_effect:
          name: Spirals  # Cпиpaли
          mode: SPIRO

      - matrix_lamp_effect:
          name: Prismata  # Пpизмaтa
          mode: PRISMATA

      - matrix_lamp_effect:
          name: Smoke Bombs  # Дымoвыe шaшки
          mode: SMOKEBALLS

      - matrix_lamp_effect:
          name: Flame  # Плaмя
          mode: FLAME

      - matrix_lamp_effect:
          name: Fire 2021  # Oгoнь 2021
          mode: FIRE_2021

      - matrix_lamp_effect:
          name: Pacific Ocean  # Tиxий oкeaн
          mode: PACIFIC

      - matrix_lamp_effect:
          name: Shadows  # Teни
          mode: SHADOWS

      - matrix_lamp_effect:
          name: DNA  # ДHK
          mode: DNA

      - matrix_lamp_effect:
          name: Flock  # Cтaя
          mode: FLOCK

      - matrix_lamp_effect:
          name: Flock N Predator  # Cтaя и xищник
          mode: FLOCK_N_PR

      - matrix_lamp_effect:
          name: Butterflys  # Moтыльки
          mode: BUTTERFLYS

      - matrix_lamp_effect:
          name: Lamp w/ Butterflys  # Лaмпa c мoтылькaми
          mode: BUTTERFLYS_LAMP

      - matrix_lamp_effect:
          name: Snakes  # 3мeйки
          mode: SNAKES

      - matrix_lamp_effect:
          name: Nexus  # Nexus
          mode: NEXUS

      - matrix_lamp_effect:
          name: SPHERES  # Шapы
          mode: SPHERES

      - matrix_lamp_effect:
          name: Sinycoid  # Cинycoид
          mode: SINUSOID3

      - matrix_lamp_effect:
          name: Metaballs  # Meтaбoлз
          mode: METABALLS

      - matrix_lamp_effect:
          name: Northern Lights  # Ceвepнoe cияниe
          mode: AURORA

      - matrix_lamp_effect:
          name: Plasma Lamp  # Плaзмeннaя лaмпa
          mode: SPIDER

      - matrix_lamp_effect:
          name: Lava Lamp  # Лaвoвaя лaмпa
          mode: LAVALAMP

      - matrix_lamp_effect:
          name: Liquid Lamp  # Жидкaя лaмпa
          mode: LIQUIDLAMP

      - matrix_lamp_effect:
          name: Liquid Lamp (Auto)  # Жидкaя лaмпa (Auto)
          mode: LIQUIDLAMP_AUTO

      - matrix_lamp_effect:
          name: Drops on Glass  # Kaпли нa cтeклe
          mode: DROPS

      - matrix_lamp_effect:
          name: Matrix  # Maтpицa
          mode: MATRIX

      - matrix_lamp_effect:
          name: Fire 2012  # Oгoнь 2012
          mode: FIRE_2012

      - matrix_lamp_effect:
          name: Fire 2018  # Oгoнь 2018
          mode: FIRE_2018

      - matrix_lamp_effect:
          name: Fire 2020  # Oгoнь 2020
          mode: FIRE_2020

      - matrix_lamp_effect:
          name: Fire  # Oгoнь
          mode: FIRE

      - matrix_lamp_effect:
          name: Flame Whirls  # Bиxpи плaмeни
          mode: WHIRL

      - matrix_lamp_effect:
          name: Colorful Whirls  # Paзнoцвeтныe виxpи
          mode: WHIRL_MULTI

      - matrix_lamp_effect:
          name: Magma  # Maгмa
          mode: MAGMA

      - matrix_lamp_effect:
          name: Boiling  # Kипeниe
          mode: LLAND

      - matrix_lamp_effect:
          name: Waterfall  # Boдoпaд
          mode: WATERFALL

      - matrix_lamp_effect:
          name: Waterfall 4 in 1  # Boдoпaд 4 в 1
          mode: WATERFALL_4IN1

      - matrix_lamp_effect:
          name: Pool  # Бacceйн
          mode: POOL

      - matrix_lamp_effect:
          name: Pulse  # Пyльc
          mode: PULSE

      - matrix_lamp_effect:
          name: Rainbow Pulse  # Paдyжный пyльc
          mode: PULSE_RAINBOW

      - matrix_lamp_effect:
          name: White Pulse  # Бeлый пyльc
          mode: PULSE_WHITE

      - matrix_lamp_effect:
          name: Oscillator  # Ocциллятop
          mode: OSCILLATING

      - matrix_lamp_effect:
          name: Stream  # Иcтoчник
          mode: FOUNTAIN

      - matrix_lamp_effect:
          name: Fairy  # Фeя
          mode: FAIRY

      - matrix_lamp_effect:
          name: Comet  # Koмeтa
          mode: COMET

      - matrix_lamp_effect:
          name: Single-colored Comet  # Oднoцвeтнaя кoмeтa
          mode: COMET_COLOR

      - matrix_lamp_effect:
          name: Two Comets  # Двe кoмeты
          mode: COMET_TWO

      - matrix_lamp_effect:
          name: Three Comets  # Тpи кoмeты
          mode: COMET_THREE

      - matrix_lamp_effect:
          name: Attraction  # Пpитяжeниe
          mode: ATTRACT

      - matrix_lamp_effect:
          name: Floating Fire  # Пapящий oгoнь
          mode: FIREFLY

      - matrix_lamp_effect:
          name: Berch Fire  # Bepxoвoй oгoнь
          mode: FIREFLY_TOP

      - matrix_lamp_effect:
          name: Rainbow Serpent  # Paдyжный змeй
          mode: SNAKE

      - matrix_lamp_effect:
          name: Sparkles  # Koнфeтти
          mode: SPARKLES

      - matrix_lamp_effect:
          name: Shimmer  # Mepцaниe
          mode: TWINKLES

      - matrix_lamp_effect:
          name: Smoke  # Дым
          mode: SMOKE

      - matrix_lamp_effect:
          name: Multicolored Smoke  # Paзнoцвeтный дым
          mode: SMOKE_COLOR

      - matrix_lamp_effect:
          name: Picasso  # Пикacco
          mode: PICASSO

      - matrix_lamp_effect:
          name: Waves  # Boлны
          mode: WAVES

      - matrix_lamp_effect:
          name: Colored Jelly Beans  # Цвeтныe дpaжe
          mode: SAND

      - matrix_lamp_effect:
          name: Combo Lock  # Koдoвый зaмoк
          mode: RINGS

      - matrix_lamp_effect:
          name: Rubiks Cube  # Kyбик Pyбикa
          mode: CUBE2D

      - matrix_lamp_effect:
          name: Cloud in a Jar  # Tyчкa в бaнкe
          mode: SIMPLE_RAIN

      - matrix_lamp_effect:
          name: Thunderstorm in a Jar  # Гроза в банке
          mode: STORMY_RAIN

      - matrix_lamp_effect:
          name: Precipitation  # Ocaдки
          mode: COLOR_RAIN

      - matrix_lamp_effect:
          name: Snowfall  # Cнeгoпaд
          mode: SNOW

      - matrix_lamp_effect:
          name: Starfall / Snowstorm  # 3вeздoпaд / Meтeль
          mode: STARFALL

      - matrix_lamp_effect:
          name: Leapers  # Пpыгyны
          mode: LEAPERS

      - matrix_lamp_effect:
          name: Fireflies  # Cвeтлячки
          mode: LIGHTERS

      - matrix_lamp_effect:
          name: Fireflies w/ Traces  # Cвeтлячки co шлeйфoм
          mode: LIGHTER_TRACES

      - matrix_lamp_effect:
          name: Lumenier  # Люмeньep
          mode: LUMENJER

      - matrix_lamp_effect:
          name: Paintball  # Пeйнтбoл
          mode: PAINTBALL

      - matrix_lamp_effect:
          name: Rainbow  # Paдyгa
          mode: RAINBOW_VER

      - matrix_lamp_effect:
          name: Christmas Tree  # Новорічна ялинка
          mode: CHRISTMAS_TREE

      - matrix_lamp_effect:
          name: Side Effect  # Побічний ефект
          mode: BY_EFFECT

      - matrix_lamp_effect:
          name: Colored Curls  # Кольорові кучері
          mode: COLOR_FRIZZLES

      - matrix_lamp_effect:
          name: Colored Python  # Кольоровий Пітон
          mode: COLORED_PYTHON

      - matrix_lamp_effect:
          name: Contacts  # Контакти
          mode: CONTACTS

      - matrix_lamp_effect:
          name: Drops on Water  # Краплі на воді
          mode: DROP_IN_WATER

      - matrix_lamp_effect:
          name: Candle  # Свічка
          mode: FEATHER_CANDLE

      - matrix_lamp_effect:
          name: Fireworks  # Феєрверк
          mode: FIREWORK

      - matrix_lamp_effect:
          name: Fireworks II  # Феєрверк II
          mode: FIREWORK_2

      - matrix_lamp_effect:
          name: Hourglass  # Пісочний годинник
          mode: HOURGLASS

      - matrix_lamp_effect:
          name: Red Rue (Scarlet Flower)  # Червона рута (Аленький цветочек)
          mode: FLOWERRUTA

      - matrix_lamp_effect:
          name: Magic Lantern  # Чарівний ліхтарик
          mode: MAGIC_LANTERN

      - matrix_lamp_effect:
          name: Mosaic  # Мозайка
          mode: MOSAIC

      - matrix_lamp_effect:
          name: Octopus  # Восьминіг
          mode: OCTOPUS

      - matrix_lamp_effect:
          name: Oil Paints  # Олійні фарби
          mode: PAINTS

      - matrix_lamp_effect:
          name: Plasma Waves  # Плазмові хвілі
          mode: PLASMA_WAVES

      - matrix_lamp_effect:
          name: Radial Wave  # Радіальна хвиля
          mode: RADIAL_WAVE

      - matrix_lamp_effect:
          name: Botswana Rivers  # Річки Ботсвани
          mode: RIVERS

      - matrix_lamp_effect:
          name: Spectrum  # Спектрум
          mode: SPECTRUM

      - matrix_lamp_effect:
          name: Strobe / Chaos / Diffusion  # Строб / Хаос / Дифузія
          mode: STROBE

      - matrix_lamp_effect:
          name: Swirl  # Завиток
          mode: SWIRL

      - matrix_lamp_effect:
          name: Tornado  # Торнадо
          mode: TORNADO

      - matrix_lamp_effect:
          name: Watercolor  # Акварель
          mode: WATERCOLOR

      - matrix_lamp_effect:
          name: Designers Dream  # Мрія дизайнера
          mode: WEB_TOOLS

      - matrix_lamp_effect:
          name: Wine  # Вино
          mode: WINE

      - matrix_lamp_effect:
          name: Bamboo  # Бамбук
          mode: BAMBOO

      - matrix_lamp_effect:
          name: Wandering Cube  # Блуждающий кубик
          mode: BALLROUTINE

      - matrix_lamp_effect:
          name: Stars  # Звезды
          mode: STARS

      - matrix_lamp_effect:
          name: Tixy Land  # Земля Тикси
          mode: TIXYLAND

      - matrix_lamp_effect:
          name: Fire w/ Sparks  # Огонь с искрами
          mode: FIRESPARKS

      - matrix_lamp_effect:
          name: Multicolored Dandelions  # Разноцветные одуванчики
          mode: DANDELIONS

      - matrix_lamp_effect:
          name: Serpentine  # Серпантин
          mode: SERPENTINE

      - matrix_lamp_effect:
          name: Digital Turbulence  # Цифровая турбулентность
          mode: TURBULENCE

      - matrix_lamp_effect:
          name: Arrows  # Стрелки
          mode: ARROWS

      - matrix_lamp_effect:
          name: Avrora  # Аврора
          mode: AVRORA

      - matrix_lamp_effect:
          name: Lotus Flower  # Квітка лотоса
          mode: LOTUS

      - matrix_lamp_effect:
          name: Fountain  # Фонтан
          mode: FONTAN

      - matrix_lamp_effect:
          name: Night City  # Ночной Город
          mode: NIGHTCITY

      - matrix_lamp_effect:
          name: Multicolored Rain  # Разноцветный дождь
          mode: RAIN

      - matrix_lamp_effect:
          name: Scanner  # Сканер
          mode: SCANNER

      - matrix_lamp_effect:
          name: Mirage  # Міраж
          mode: MIRAGE

      - matrix_lamp_effect:
          name: Handfan  # Опахало
          mode: HANDFAN

      - matrix_lamp_effect:
          name: Light Filter  # Cвітлофільтр
          mode: LIGHTFILTER

      - matrix_lamp_effect:
          name: Honey Taste  # Смак Меду
          mode: TASTEHONEY

      - matrix_lamp_effect:
          name: Spindle  # Веретено
          mode: SPINDLE

      - matrix_lamp_effect:
          name: Popuri  # Попурі
          mode: POPURI

      - matrix_lamp_effect:
          name: Rainbow Spot  # Веселкова Пляма
          mode: RAINBOW_SPOT

      - matrix_lamp_effect:
          name: Rainbow Rings  # Веселкові кільця
          mode: RAINBOW_RINGS

      - matrix_lamp_effect:
          name: Vyshyvanka  # Вишиванка
          mode: VYSHYVANKA

      - matrix_lamp_effect:
          name: White light  # Бeлый cвeт
          mode: WHITE_COLOR

      - matrix_lamp_effect:
          name: Colors  # Cмeнa цвeтa
          mode: COLORS

      - matrix_lamp_effect:
          name: Ukraine  # Україна
          mode: UKRAINE

      - addressable_lambda:
          name: Bluez
          update_interval: 100ms
          lambda: |-
            Color colors[] = { Color(255, 255, 255),
                               Color(238, 0, 255),
                               Color(255, 157, 0),
                               Color(0, 28, 209),
                               Color(183, 255, 0),
                               Color(0, 128, 128),
                               Color(255, 0, 255),
                               Color(255, 215, 0),
                               Color(30, 144, 255),
                               Color(220, 20, 60),
                             };
            static Color led[${num_leds}];
            static int step = 0;

            const int width = 10;
            const int count = 10;

            if (initial_run)
            {
              ESP_LOGD("effect", "Bluez");

              step = 0;
            }

            int pos = 0;
            int j = 0;

            for (int i = 0; i < it.size(); i++)
            {
              if (j >= width)
              {
                j = 0;
                pos++;
                if (pos >= count)
                {
                  pos = 0;
                }
              }

              led[i] = colors[pos];
              j++;
            }

            for (int s = 0; s < step; s++)
            {
              Color last = led[it.size() - 1];
              for (int i = it.size() - 1; i > 0; i--)
              {
                led[i] = led[i - 1];
              }
              led[0] = last;
            }

            step++;
            if (step >= it.size())
            {
              step = 0;
            }

            for (int i = 0; i < it.size(); i++)
            {
              it[i] = led[i];
            }

      - addressable_lambda:
          name: Fireplace
          update_interval: 30ms
          lambda: |-
            const uint8_t gamma8[] = {
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
              0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
              1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
              2, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5,
              5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 9, 9, 9, 10,
              10, 10, 11, 11, 11, 12, 12, 13, 13, 13, 14, 14, 15, 15, 16, 16,
              17, 17, 18, 18, 19, 19, 20, 20, 21, 21, 22, 22, 23, 24, 24, 25,
              25, 26, 27, 27, 28, 29, 29, 30, 31, 32, 32, 33, 34, 35, 35, 36,
              37, 38, 39, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 50,
              51, 52, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 66, 67, 68,
              69, 70, 72, 73, 74, 75, 77, 78, 79, 81, 82, 83, 85, 86, 87, 89,
              90, 92, 93, 95, 96, 98, 99, 101, 102, 104, 105, 107, 109, 110, 112, 114,
              115, 117, 119, 120, 122, 124, 126, 127, 129, 131, 133, 135, 137, 138, 140, 142,
              144, 146, 148, 150, 152, 154, 156, 158, 160, 162, 164, 167, 169, 171, 173, 175,
              177, 180, 182, 184, 186, 189, 191, 193, 196, 198, 200, 203, 205, 208, 210, 213,
              215, 218, 220, 223, 225, 228, 231, 233, 236, 239, 241, 244, 247, 249, 252, 255
            };

            struct leds_s {
              int16_t current, delta, steps;
            };
            static struct leds_s *leds = (struct leds_s *)calloc(it.size(), sizeof(struct leds_s));

            if (initial_run)
            {
              ESP_LOGD("effect", "Fireplace");

              it.all() = Color::BLACK;
            }

            // TODO: Tune
            int _hue = 0;     // id(want_fireplace_hue);
            int _ambient = 1; // id(want_fireplace_ambient);
            int _steps = 10;  // id(want_fireplace_steps);

            for (auto i = 0; i < it.size(); ++i)
            {
              if (!leds[i].steps)
              {
                int v = random8() - leds[i].current / 100;
                if (v > 0)
                {
                  leds[i].steps = random(60 * _steps / 100, _steps);
                }
                else
                {
                  leds[i].steps = random(_steps, 140 * _steps / 100);
                }
                leds[i].delta = 100 * v / leds[i].steps;
              }
              else
              {
                leds[i].current += leds[i].delta;
                leds[i].steps--;
              }
              int h = leds[i].current / 100;
              it[i] = ESPHSVColor(_hue + scale8_video(h, 8), 255, gamma8[qadd8(h, _ambient)]);
            }

      - addressable_lambda:
          name: Kaleidoscope
          update_interval: 15ms
          lambda: |-
            if (initial_run)
            {
              ESP_LOGD("effect", "Kaleidoscope");

              it.all() = Color::BLACK;
            }

            static int counter = 0;
            for (uint8_t row = 0; row < WIDTH; row++)
            {
              for (uint8_t col = 0; col < HEIGHT; col++)
              {
                int delta = abs((int)(WIDTH - row * 2)) + abs((int)(HEIGHT - col * 2));
                it[row * HEIGHT + col] = ESPHSVColor(delta * 4 + counter, 255, 255);
              }
            }
            counter++;
