substitutions:
  project_name: "ajs.Light - Matrix Lamp"
  project_version: "1.1.13"
  comment: "ESPHome Matrix Lamp"

esphome:
  libraries:
    - fastled/FastLED @ 3.6.0
  on_boot:
    priority: -100
    then:
      # - light.turn_off:
      #     id: neopixel_led
      - delay: 5s
      - logger.log:
          format: "${name} started, LED: ${type_leds}:${num_leds}:${pin_leds}, Effects: %d Reboot: ${reboot_timeout}"
          args: ['id(neopixel_led)->get_effects().size()']
          level: INFO
          tag: start

external_components:
  - source:
      type: local
      path: components
    components: [matrix_lamp]

matrix_lamp:
  id: matrix
  width: 16
  height: 16
  random: true
  scale_id: matrix_scale
  speed_id: matrix_speed

number:
  # Matrix Orientation
  - platform: template
    name: ${name} Matrix Orientation
    icon: mdi:autorenew
    min_value: 1
    max_value: 8
    step: 1
    optimistic: true
    id: matrix_orientation
    initial_value: 4
    mode: slider
    entity_category: config
    disabled_by_default: true
    restore_value: true
    on_value:
      then:
        - lambda: |-
            id(matrix).SetMatrixOrientation(x);

  # Matrix Settings
  - platform: template
    name: ${name} Effect Speed
    icon: mdi:speedometer
    min_value: 0
    max_value: 255
    step: 1
    optimistic: true
    id: matrix_speed
    initial_value: 128
    mode: slider
    entity_category: config

  - platform: template
    name: ${name} Effect Scale
    icon: mdi:drag-variant
    min_value: 0
    max_value: 100
    step: 1
    optimistic: true
    id: matrix_scale
    initial_value: 50
    mode: slider
    entity_category: config
